name: mi primer pipeline
on:
  push:
    branches:[ main ]
jobs:
    verificacion:
        runs-on: ubuntu-latest
        steps:
         - name: 1. descargar codigo
            uses: actions/checkout@v4

         - name: 2. instalar node.js
            uses: actions/setup-node@v4
            with:
                node-version: '20'
                cache: 'npm'

         - name: 3. instalar dependencias del proyecto
          run: npm install

         - name: 4. ejecutar pruebas
          run: npm test

         - name: 5. mensaje final
          run: echo "Pipeline ejecutado correctamente"